### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by RobinKnipe** [alphagov/data-standards-authority#14]
Hi :wave: good to see this in the presentation earlier this week! I thought this might help, [some work we did to check for broken links](https://github.com/UKHomeOffice/lev-web/blob/aeeb6cd5ef7321059cfc200b0b3c0abf18c739d6/test/acceptance/spec/06-link-checker.js).

**Comment by charlesbaird-dsa** [comment]
Thanks @RobinKnipe, we'll definitely use that in future!
