### ISSUE TITLE
Re: 'Taxonomies'

### ISSUE THREAD

**Issue by bellclaireons** [alphagov/data-standards-authority#172]
Feedback on 'Taxonomies' (https://alphagov.github.io/data-standards-authority/taxonomies/)

The font page of the Taxonomies catalogue shows all 3 taxonomies as being endorsed, when opening the taxonomy documents themselves, 2 of them still show as "In review" - these are The Occupational Information Network and the SOC

**Comment by nahteb** [comment]
Hello, thanks for raising - these should all be showing as Endorsed now
