### ISSUE TITLE
Re: 'Standards Catalogue'

### ISSUE THREAD

**Issue by benaldo1975** [alphagov/data-standards-authority#32]
Hi - would the Service standard (https://www.gov.uk/service-manual/service-standard) be on here, or are these all data-specific standards? 

Feedback on 'Standards Catalogue' (https://alphagov.github.io/data-standards-authority/data-standards-authority/standards-catalogue/standards/)

**Comment by charlesbaird-dsa** [comment]
Hi Ben - at the moment it's just data standards, although possibly as the service standard evolves and starts to include data specific elements there would be a case to include it?
