### ISSUE TITLE
Standards Catalogue: Report Problem problem

### ISSUE THREAD

**Issue by edent** [alphagov/data-standards-authority#7]
Link ion the [360 page](https://alphagov.github.io/data-standards-authority/standards-catalogue/standards/domainspecific/360giving/#360giving-schema) currently `https://github.com/https://github.com/alphagov/data-standards-authority//issues/new?labels=bug&title=Re:%20%27%27&body=Problem%20with%20%27%27%20(https://alphagov.github.io/data-standards-authority/standards-catalogue//standards/domainspecific/360giving/)`

From https://github.com/alphagov/data-standards-authority/blob/266f9d97108efeb7f94490a19fd877a3efdb054a/standards-catalogue/lib/govuk_tech_docs/contribution_banner.rb#L25 I think

**Comment by charlesbaird-dsa** [comment]
Ah, you're quick! That was a config issue that should now be resolved; but the 'view source' link is stil problematic, working on that...
