### ISSUE TITLE
Standards Catalogue - broken view source

### ISSUE THREAD

**Issue by edent** [alphagov/data-standards-authority#9]
Problem with 'OpenReferralUK' (https://alphagov.github.io/data-standards-authority/standards-catalogue/standards/servicedesign/openreferraluk/)

The "View Source" link goes to 
* https://github.com/alphagov/data-standards-authority//blob/main/source/standards/servicedesign/openreferraluk/index.html.md
It should go to 
* https://github.com/alphagov/data-standards-authority/blob/main/standards-catalogue/source/standards/servicedesign/openreferraluk/index.html.md

I think the errant file is from https://github.com/alphagov/data-standards-authority/blob/main/standards-catalogue/lib/govuk_tech_docs/contribution_banner.rb#L55

**Comment by charlesbaird-dsa** [comment]
Fixed by #19 (at last)
